spring.application.name=veterinaria

spring.datasource.url=jdbc:postgresql://localhost:5432/Veterinaria
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET:huellitas2026_clave_super_secreta_larga_para_jwt}
jwt.expiration=${JWT_EXPIRATION:86400000}